### ISSUE TITLE
Why is the sum of Success and Fail count not equal to the number of total requests?

### ISSUE THREAD

**Issue by zhengminlai** [EricQAQ/tikv-bench-tool#1]
Hi Eric, first of all, thanks for you benchmark tikv tool, it really helps me a lot. But I have a question.

Why is the sum of Success and Fail count not equal to the number of total requests?

**Comment by EricQAQ** [comment]
Hi, please try the latest version. Sorry for late to update..

**Comment by zhengminlai** [comment]
thank u
